### ISSUE TITLE
Every time a `HypixelGame` wants to retrieve information they have to provide the prefix to the `JSONObject`.

### ISSUE THREAD

**Issue by unpluggedsam** [hypixelapiwrapper/hypixel-api-java#35]
As I began planning out on how `HypixelGame` Objects will retrieve data I realized that each time they will have to provide the prefix based on the mode. (Check out the `bedwars` package for context.) This seems very error prone and inefficient.

 Initially I'm thinking of having a class that holds the game type enum, and the `JSONObject`. It would be initiated on the construction of the class and would be passed in a `JSONObject` and a Mode enum.  That class would then have a method called, retrieveData(), or something, that would take in a String of the location of the data being retrieved. It would then automatically [prepend ](https://www.techopedia.com/definition/31511/prepend#:~:text=Prepend%20is%20a%20word%20that,programming%20and%20in%20automated%20processes.) the prefix. 

I was wondering if this feels necessary or if it would just over complicate the program.

**Comment by TheNullicorn** [comment]
Still thinking about the question itself, but just wanted to add that mode-based prefixes are only used in bedwars and duels as far as I can tell.

**Comment by Mqlvin** [comment]
Considering we are aiming for consistency, maybe it's best to start on two or three other games and see how we plan those out. We may as well not to use this `mode enum` design for bedwars and duels if all the other games in the wrapper are built on a different design (and use this different design for duels/bedwars).

**Comment by unpluggedsam** [comment]
I think this means that for now we will not be using a utility class and will manually enter the JSON inputs. If in the future it seems like that would be useful it won't be very hard to implement.
