### ISSUE TITLE
JSON handling

### ISSUE THREAD

**Issue by Deftu** [hypixelapiwrapper/hypixel-api-java#37]
Is there any reason in particular this project uses `org.json` instead of something like Jackson or GSON? Those are much faster, more common (especially in Forge 1.8 modding) and are still maintained. I don't really see that many benefits personally to using this older lib.

**Comment by Black-Plasma** [comment]
Initially it was chosen for simplicity. If performance becomes a bottleneck we have already talked about adopting Jackson though.

**Comment by Deftu** [comment]
Personally I'd prefer if it was migrated to GSON, but a switch to Jackson would be very welcome.

**Comment by Black-Plasma** [comment]
If we make a switch we'll probably use Jackson.
To quote Nullicorn here:
> I saw Gson suggested, but Jackson outperforms it in all benchmarks I'm seeing online

But as I said performance hasn't been a bottleneck yet and we are still very early in the project.

**Comment by unpluggedsam** [comment]
I would like to add that performance will be very important and it would probably be easier to switch over now rather than later.

**Comment by Black-Plasma** [comment]
I created a discussion
