### ISSUE TITLE
Handle a blank API field on data retrieval

### ISSUE THREAD

**Issue by unpluggedsam** [hypixelapiwrapper/hypixel-api-java#56]
The Hypixel API does not provide every field for players who do not have statistics in certain fields. For example, my account (Zehc2), does not have the field `whither_kills_bedwars` because I do not have any whither kills in Bedwars. The code will then throw an error because the `JSONObject` does not have the `whither_kills_bedwars` field. Ideas on how to handle this?

**Comment by TheNullicorn** [comment]
Why not just use default values? For your example, if you don't have that field, then it means you haven't killed anyone from the withering affect, and thus is would be `0`.

**Comment by unpluggedsam** [comment]
Well yes, that would be ideal but the problem is *the field does not exist in the `JSONObject`*. Therefor, it would throw an exception. We could handle an exception for each method and return a default value but that feels very redundant.

**Comment by NotInsertIGN** [comment]
`JSONObject`s have a method called `#has`, which takes in a String of the field's name and returns a boolean.
```java
public int getWitherKills() {
    if(stats.has("wither_kills_bedwars")) {
        return stats.getInt("wither_kills_bedwars");
    }
    return 0;
}
```

**Comment by unpluggedsam** [comment]
@NotInsertIGN 
Seems like a good solution, except I wouldn't want to implement it in every method. We could go back to the solution in #35 where we have a method that automatically prepends the prefix. It could also then provide the check to see if the field exists. 

The only problem that I can think of at the moment is if the key that the method provides has a typo it wouldn't give an error. I don't think there is a feasible solution for it but it would be mildly annoying.

**Comment by TheNullicorn** [comment]
> I don't think there is a feasible solution for it but it would be mildly annoying.

Unit testing?

**Comment by unpluggedsam** [comment]
> > I don't think there is a feasible solution for it but it would be mildly annoying.
> 
> Unit testing?

Still wouldn't throw an error.

**Comment by TheNullicorn** [comment]
> > > I don't think there is a feasible solution for it but it would be mildly annoying.
> > 
> > 
> > Unit testing?
> 
> Still wouldn't throw an error.

As assertion would catch that the method's not returning what's in the data though. That's the point of testing it

**Comment by unpluggedsam** [comment]
> > > > I don't think there is a feasible solution for it but it would be mildly annoying.
> > > 
> > > 
> > > Unit testing?
> > 
> > 
> > Still wouldn't throw an error.
> 
> As assertion would catch that the method's not returning what's in the data though. That's the point of testing it

Ah, yes, you're right. How do we feel about implementing #35 though?

**Comment by NotInsertIGN** [comment]
@unpluggedsam you could also use a ternary operator for the same thing.

**Comment by NotInsertIGN** [comment]
@unpluggedsam We could actually also create an annotation for that... if you feel it necessary ofc

**Comment by unpluggedsam** [comment]
> @unpluggedsam We could actually also create an annotation for that... if you feel it necessary ofc

Can you elaborate?

**Comment by NotInsertIGN** [comment]
> > @unpluggedsam We could actually also create an annotation for that... if you feel it necessary ofc
> 
> Can you elaborate?
Below is a quick example of my thought process in some pseudo code.
```java
@Annotation(object = stats, field = "wither_kills_bedwars", type = int.class) // annotations are named in PascalCase
public int getWitherKills() {
    return stats.getInt("wither_kills_bedwars");
}
```
This would, in theory, check the `stats` object, and check whether it had the value in the `field` argument, in this case, `wither_kills_bedwars`. If it does, it doesn't do anything; if it doesn't, it overrides the method and returns the value set for the given `type`

**Comment by unpluggedsam** [comment]
> @unpluggedsam you could also use a ternary operator for the same thing.

Well yes, but that wouldn't really solve the redundancy problem.

**Comment by unpluggedsam** [comment]
> ```java
> 
> ```

That seems like a good solution, I would have no idea how you would go about implementing it. How would the annotation override the methods return value? Also, if it is possible we could just have the annotation do all the work and if the value is present in the API return the value.
